# 데몬셋 = 디플로이먼트의 replicas가 노드 수만큼 정해져 있는 형태 
# 노드를 관리하는 파드로 사용

#콘피그맵 = 설정 용도로 사용

#PV = 볼륨 스토리지 중 하나
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.10
    path: /nfs_shared