# 데몬셋 = 디플로이먼트의 replicas가 노드 수만큼 정해져 있는 형태 
# 노드를 관리하는 파드로 사용

#콘피그맵 = 설정 용도로 사용

#PV = 볼륨 스토리지 중 하나
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 100Mi #쓸 수 있는 사용량을 레이블에 붙임
  accessModes: #PV 사용방식 정의
    - ReadWriteMany #여러 개의 노드가 읽고 쓸 수 있도록 마운트 ReadWriteOne 이나 ReadOnlyMany 옵션이 있음
  persistentVolumeReclaimPolicy: Retain #PVC가 제거됐을 때 PV가 작동하는 방법 정의 Retain = 유지 Delete, Recycle옵션이 있음
  nfs: #NFS 서버의 연결 위치에 대한 설정
    server: 192.168.1.10
    path: /nfs_shared