pipline{
    agent any
    stages{
        stage('git pull'){
            steps{
                git url: 'https://github.com/akm4545/k8s-GitOps-study.git', branch: 'main'
            }
        }
        stage('k8s deploy'){
            steps{
                kubernetesDeploy(kubeconfigId: 'kubeconfig', configs: '*.yaml')
            }
        }
    }
}