apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spce:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        #프로메테우스의 익스포터가 메트릭을 수집하기 위해 api 서버에 등ㄺ
      annotations:
        prometheus.io/port: "80"
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: nginx
        image: sysnet4admin/nginx-status
        ports:
        - containerPort: 80
